"""empty message

Revision ID: e44b16e79253
Revises: cba96133ed04
Create Date: 2025-11-07 13:19:12.587427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e44b16e79253'
down_revision: Union[str, Sequence[str], None] = 'cba96133ed04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('starting', sa.Integer(), nullable=False),
    sa.Column('growth', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('question_difficulty', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('question_choices', sa.JSON(), nullable=False),
    sa.Column('correct_answer', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statements',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('valuation', sa.BigInteger(), nullable=False),
    sa.Column('growth', sa.Float(), nullable=False),
    sa.Column('term', sa.Integer(), nullable=True),
    sa.Column('liab_status', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('trophies', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('retirement_age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('employment_age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('career_name', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('career_starting', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('career_growth', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('children', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('monthly_spending', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'monthly_spending')
    op.drop_column('users', 'children')
    op.drop_column('users', 'career_growth')
    op.drop_column('users', 'career_starting')
    op.drop_column('users', 'career_name')
    op.drop_column('users', 'employment_age')
    op.drop_column('users', 'retirement_age')
    op.drop_column('users', 'trophies')
    op.drop_table('statements')
    op.drop_table('questions')
    op.drop_table('jobs')
    # ### end Alembic commands ###
